name = "smokeshow-staging"
account_id = "d6252a570c309c113744c9e11317e271"
workers_dev = true
main = "worker/index.mjs"
compatibility_date = "2022-07-15"
kv_namespaces = [
  {binding="STORAGE", id="b4ba1fc5fb614af7be37ad63a42c218d", preview_id="6b60f496af50470784eaf3a118032148"}
]

[build]
command = "npm run build"
watch_dir = "src"

[vars]
DEBUG = "TRUE"
# POSTGREST_ROOT and POSTGREST_APIKEY are set by CI

[env.production]
name = "smokeshow"
workers_dev = false
route = "smokeshow.helpmanual.io/*"
kv_namespaces = [
  {binding = "STORAGE", id = "74015bfa1d2443dfaaba49276b0d4310"}
]
[env.production.vars]
DEBUG = "FALSE"
# POSTGREST_ROOT and POSTGREST_APIKEY are set by CI
